### ISSUE TITLE
Clan chat message structure

### ISSUE THREAD

**Issue by ghost** [royale-proxy/cr-messages#1]
Hi!
I'm currently working on the clan chat message structure.
The thing is that the messages are obfuscated, so we have to go on low-level contents.
This is a raw chat message content
`5ef800003800000200819eec561d8ed0051d8ed00500000005416c676f7506040000000000194a276169206c6f6f746572206c65207072696e6365203a2d29`

`5ef8` = `24312` is the message type id (AllianceStreamEntry by cocdp).

In the part `00003800000200819eec561d8ed0` there is normally the post time, but I didn't found it...

`416c676f750604` = Algou, the author's name

`0000000000194a` is a separator (at least 0000000000 I think)

`276169206c6f6f746572206c65207072696e6365203a2d29` = "J'ai looter le prince :-)", it's the message content

How can we get this with the json selector?

**Comment by akirarat** [comment]
Have to write a CR specific field type by changing coc/message/reader.py.

**Comment by srabouin** [comment]
This was added in https://github.com/royale-proxy/cr-messages/commit/7806c946b49de459e0da7921a4e874b501b320f8
