### ISSUE TITLE
Need combat-related messages' structures

### ISSUE THREAD

**Issue by Pr0methean** [royale-proxy/cr-messages#11]
I'm not sure this is the best way to reach you about this, but here goes.

I'm looking to create a tool that can extract blow-by-blow combat logs (like what World of Warcraft produces with the /combatlog command) as a first step toward automating after-action review. I figure the safest and easiest way to do this, despite requiring a rooted/jailbroken device, is with a packet sniffer running as a separate app. But to do this, I need definitions for the messages that carry unit movement, attacks and casting. How close are you to deciphering those?

**Comment by srabouin** [comment]
You can't do it, the only thing the game server tells you is where the player dropped the card x/y coords. The game server doesn't do any logic, the client does the logic.
