### ISSUE TITLE
Beta structures

### ISSUE THREAD

**Issue by ghost** [royale-proxy/cr-messages#2]
I tried to figure out some message structures, but I encountered some problems, which I hope someone else already figured out :).

I started with the message pair `14324 (SearchAlliances)` and `24310 (AllianceList)`.
First my "beta" structures:

``` json
{
    "id": 14324,
    "name": "SearchAlliances",
    "fields": [
        {"name": "searchString", "type": "STRING"},
        {"name": "clanLocation", "type": "?3BYTE"},
        {"name": "minMembers", "type": "INT"},
        {"name": "maxMembers", "type": "INT"},
        {"type": "BYTE"},
        {"type": "BYTE"},
        {"name": "trophyLimit", "type": "2BYTE"},
        {"name": "joinable", "type": "BOOLEAN"},
        {"type": "INT"},
        {"type": "INT"}
    ]
}
```

``` json
{
   "id": 24310,
   "name": "AllianceList",
   "fields": [
      {"name": "searchString", "type": "STRING"},
      {"name": "searchEntries", "type": "SearchEntry[]"}
   ]
}
```

``` json
{
   "name": "SearchEntry",
   "fields": [
      {"name": "clanId", "type": "LONG"},
      {"name": "clanName", "type": "STRING"},
      {"name": "clanBadge", "type": "3BYTE"},
      {"name": "memberCount", "type": "BYTE"},
      {"name": "trophies", "type": "2BYTE"},
      {"type": "BYTE"},
      {"name": "requiredTrophies", "type": "?2BYTE"},
      {"type": "BYTE"},
      {"type": "2BYTE"},
      {"type": "2BYTE"},
      {"type": "2BYTE"},
      {"type": "INT"}
   ]
}
```
1. For what I saw, message fields can have sizes of 1, 2, 3, 4 and 8 bytes. For example `memberCount` can only be max 50 so only 1 byte is used. No big problem, but it makes it hard reading those hex dumps.
2. Many values are somehow obfuscated and can't be extracted directly. For example `trophies`, `gold`, `gems`, etc.. Again from looking at the hex dumps of `24310 (AllianceList)` the `trophies` field needs some math to get the real value. Something like:
   `base_value + trophy_count * factor`
   But `base_value`and `factor` changes if you compare it to different clans. Same with `requiredTrophies`, but a different formula.
   Understanding the message reader needs some debugging I guess. Maybe someone has already done this?
3. The last thing the optional field changed. For example `clanLocation` can have a length between 1-3.
   `
   Any = 0x00,
   Europe = 0x3900,
   Zimbabwe = 0x398404
   `
   Depending on the value the length changes of those fields. I can handle that, but there are additional problems. For example `SearchEntry` does not work as it is, because the length also changes and I don't know why, mainly because of problem 2 und 3 :).

So does anyone has some hints/tips how to handle these problems or has someone done some debugging?

**Comment by akirarat** [comment]
I'm looking into hooking up Frida to the app. Static network and assembly analysis is not very helpful at this point.

**Comment by srabouin** [comment]
@akirarat figured out the VARINT / RRSINT32 -- so this shouldn't be a puzzle anymore, I have done the search alliance message and it's working well :)
