### ISSUE TITLE
Proxy setting problem

### ISSUE THREAD

**Issue by Asdamp** [royale-proxy/cr-messages#4]
Hi, sorry if i open an issue, but is the only way to get in touch with you.
 i'm a developer and i'm really interested in reverse clash royale protocol. I love clash royale and on reddit i usually datamine csv files. However i want to learn more. I know python, and with some help i can work on this project.
First of all i want to set up the proxy. I used a modified version of coc-patcher to try to patch the apk file. However the url is a problem to me. i really don't know what to write as the url in the json config file. 
Can youi help me to setup my environment?

**Comment by ghost** [comment]
Unfortunately, I'm not maintaining this anymore, so I recommend you speak to @akirarat as he's taken over. Although, just make sure you've got a patched APK, then try running https://github.com/clugh/coc-proxy as the Clash of Clans protocol is similar to the Clash Royale protocol

**Comment by akirarat** [comment]
Hey there Asdamp. Great work in reverse engineering the CSV file on reddit. I'll help you out. Come chat with me on discord.

https://discord.gg/m8qHnSs
