### ISSUE TITLE
.

### ISSUE THREAD

**Issue by esad65** [royale-proxy/cr-messages#8]

**Comment by BerkanYildiz** [comment]
@esad65 , You should delete this download link right now ;)

**Comment by esad65** [comment]
Aha, so you only ignore on skype

**Comment by BerkanYildiz** [comment]
@esad65 I don't accept kids anymore.

**Comment by esad65** [comment]
Kids? I only Asked you an normal question, but youre too fame to answer. EBen not an simple no.

**Comment by esad65** [comment]
No problem i will share your GRS to everyone :)

**Comment by BerkanYildiz** [comment]
@esad65 Yea, share it ;) 1.3.2 is so famous 😂

**Comment by esad65** [comment]
ok
